-- ==============================================================================
-- SEED DATA E-BOOK DIGITAL LENGKAP & REALISTIS UNTUK SLiMS EBOOK (senayan_ebook)
-- Berstandar RDA (Resource Description and Access), DDC, dan Akses Terbuka SLiMS
-- ==============================================================================

-- 1. Penulis (mst_author)
INSERT IGNORE INTO `mst_author` (`author_id`, `author_name`, `authority_type`, `input_date`, `last_update`) VALUES
(201, 'Martin Fowler', 'p', NOW(), NOW()),
(202, 'Chris Richardson', 'p', NOW(), NOW()),
(203, 'Dr. Ir. Rian Pratama, M.Sc.', 'p', NOW(), NOW()),
(204, 'Andrew Ng, Ph.D.', 'p', NOW(), NOW()),
(205, 'Alex Xu', 'p', NOW(), NOW()),
(206, 'Sahn Lam', 'p', NOW(), NOW()),
(207, 'Eko Kurniawan Khannedy', 'p', NOW(), NOW()),
(208, 'Sandhika Galih', 'p', NOW(), NOW()),
(209, 'Robert C. Martin (Uncle Bob)', 'p', NOW(), NOW()),
(210, 'Kevin Mitnick', 'p', NOW(), NOW()),
(211, 'Brendan Burns', 'p', NOW(), NOW()),
(212, 'Kelsey Hightower', 'p', NOW(), NOW()),
(213, 'Aurélien Géron', 'p', NOW(), NOW()),
(214, 'Dr. Ayu Lestari, M.T.I.', 'p', NOW(), NOW()),
(215, 'Don Norman', 'p', NOW(), NOW()),
(216, 'Gita Wirjawan', 'p', NOW(), NOW()),
(217, 'Eric Ries', 'p', NOW(), NOW()),
(218, 'Donny Prakoso', 'p', NOW(), NOW()),
(219, 'Angela Yu', 'p', NOW(), NOW()),
(220, 'Baron Schwartz', 'p', NOW(), NOW()),
(221, 'Satya Nadella', 'p', NOW(), NOW()),
(222, 'Amy Edmondson', 'p', NOW(), NOW()),
(223, 'Dirk Slama', 'p', NOW(), NOW()),
(224, 'Prof. Dr. Ir. Suhono H. Supangkat', 'p', NOW(), NOW());

-- 2. Penerbit (mst_publisher)
INSERT IGNORE INTO `mst_publisher` (`publisher_id`, `publisher_name`, `input_date`, `last_update`) VALUES
(201, 'O Reilly Media, Inc.', NOW(), NOW()),
(202, 'Prentice Hall International', NOW(), NOW()),
(203, 'Galura Tech Publishing', NOW(), NOW()),
(204, 'ByteByteGo Publishing Press', NOW(), NOW()),
(205, 'CyberShield & Network Press', NOW(), NOW()),
(206, 'Elex Media Komputindo Digital', NOW(), NOW()),
(207, 'Harper Business International', NOW(), NOW()),
(208, 'Springer Nature Digital', NOW(), NOW()),
(209, 'Penerbit Salemba Humanika', NOW(), NOW()),
(210, 'Galura Academic Press', NOW(), NOW());

-- 3. Tempat Terbit (mst_place)
INSERT IGNORE INTO `mst_place` (`place_id`, `place_name`, `input_date`, `last_update`) VALUES
(201, 'San Francisco, CA', NOW(), NOW()),
(202, 'Sebastopol, CA', NOW(), NOW()),
(203, 'Jakarta', NOW(), NOW()),
(204, 'Bandung', NOW(), NOW()),
(205, 'Boston, MA', NOW(), NOW()),
(206, 'New York, NY', NOW(), NOW()),
(207, 'Berlin', NOW(), NOW()),
(208, 'London', NOW(), NOW());

-- 4. Topik / Subjek (mst_topic)
INSERT IGNORE INTO `mst_topic` (`topic_id`, `topic`, `topic_type`, `input_date`, `last_update`) VALUES
(201, 'Cloud Architecture & Microservices', 't', NOW(), NOW()),
(202, 'Artificial Intelligence & Large Language Models', 't', NOW(), NOW()),
(203, 'System Design & Scalability', 't', NOW(), NOW()),
(204, 'Full-Stack Web Development', 't', NOW(), NOW()),
(205, 'Software Engineering Clean Code', 't', NOW(), NOW()),
(206, 'Cybersecurity & Ethical Hacking', 't', NOW(), NOW()),
(207, 'DevOps & Site Reliability Engineering', 't', NOW(), NOW()),
(208, 'Data Science & Machine Learning', 't', NOW(), NOW()),
(209, 'UI/UX Design Systems', 't', NOW(), NOW()),
(210, 'Digital Business & Tech Startups', 't', NOW(), NOW()),
(211, 'Mobile App Engineering', 't', NOW(), NOW()),
(212, 'Database Internals & Caching', 't', NOW(), NOW()),
(213, 'Digital Business & Leadership', 't', NOW(), NOW()),
(214, 'Internet of Things & Edge Computing', 't', NOW(), NOW()),
(215, 'Research Methodology & Academic Writing', 't', NOW(), NOW());

-- 5. Bibliografi E-Book Digital (biblio)
INSERT INTO `biblio` (
  `biblio_id`, `gmd_id`, `title`, `sor`, `edition`, `isbn_issn`, `publisher_id`, `publish_year`,
  `collation`, `series_title`, `call_number`, `language_id`, `source`, `publish_place_id`,
  `classification`, `notes`, `image`, `file_att`, `opac_hide`, `promoted`, `labels`, `frequency_id`,
  `spec_detail_info`, `content_type_id`, `media_type_id`, `carrier_type_id`, `input_date`, `last_update`, `uid`
) VALUES
(
  201, 30,
  '[E-Book] Arsitektur Microservices & Cloud-Native: Desain, Pola, dan Implementasi Produksi Skala Besar',
  'Martin Fowler, Chris Richardson ; editor teknis, Dr. Ir. Rian Pratama, M.Sc.',
  'Edisi Digital Ke-2 (Revisi Lengkap)',
  '978-623-01-3890-5', 203, '2024',
  '1 file PDF (xxviii, 482 hlm. : ilus. ; 25 cm)',
  'Seri Arsitektur Cloud & Rekayasa Perangkat Lunak Modern; Jilid 1',
  'EB 004.678 FOW a', 'id', 'pembelian', 203, '004.678',
  'Buku ini menyajikan rujukan paling komprehensif bagi arsitek perangkat lunak dan insinyur senior yang hendak merancang, memigrasikan, dan mengoperasikan ekosistem microservices pada skala produksi tinggi. Dimulai dari identifikasi batas-batas kontekstual (bounded contexts) Domain-Driven Design hingga implementasi pola Saga untuk transaksi terdistribusi. Dilengkapi studi kasus nyata implementasi orkestrasi container menggunakan Kubernetes, streaming data asinkron Apache Kafka, service mesh Istio, API gateway Envoy, serta metrik observabilitas terintegrasi OpenTelemetry, Prometheus, dan Grafana.',
  NULL, 'microservices_cloud_native.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  202, 30,
  '[E-Book] Rekayasa Prompt & Implementasi LLM Modern: Panduan Komprehensif AI Generatif Mandiri',
  'Dr. Ir. Rian Pratama, M.Sc., Andrew Ng, Ph.D. ; editor, Tim Lab AI Galura',
  'Edisi Digital 2024',
  '978-623-01-3891-2', 203, '2024',
  '1 file PDF (xxiv, 396 hlm. : ilus. ; 25 cm)',
  'Seri Kecerdasan Artifisial Tingkat Lanjut; Jilid 2',
  'EB 006.31 PRA r', 'id', 'pembelian', 203, '006.31',
  'Karya ini mengupas tuntas paradigma rekayasa prompt dan integrasi sistem model bahasa besar (LLM) untuk kebutuhan industri modern. Membahas formulasi prompt deterministik, teknik pemikiran berantai (Chain-of-Thought), penalaran ReAct, dan mitigasi halusinasi model pada domain sensitif seperti hukum, medis, dan perbankan. Fokus mendalam diberikan pada arsitektur Retrieval-Augmented Generation (RAG) hibrida yang memadukan pencarian semantik vektor dengan BM25 lexikal, re-ranking Cross-Encoder, serta implementasi agen cerdas yang mampu mengeksekusi alat komputasi eksternal secara terverifikasi.',
  NULL, 'prompt_engineering_llm.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  203, 30,
  '[E-Book] System Design Interview: Panduan Arsitektur Sistem Skala Ratusan Juta Pengguna',
  'Alex Xu, Sahn Lam ; alih bahasa, Eko Kurniawan Khannedy',
  'Vol. 2 Digital Edition',
  '978-1-7360491-1-2', 204, '2024',
  '1 file PDF (xxxii, 540 hlm. : ilus. ; 25 cm)',
  'Seri Standar Arsitektur Sistem Global; Jilid 2',
  'EB 004.22 XU s', 'id', 'pembelian', 201, '004.22',
  'Buku rujukan global yang telah membantu ribuan insinyur dan arsitek sistem melewati wawancara teknis tingkat staf dan prinsipal di perusahaan teknologi terkemuka dunia. Menjelaskan langkah demi langkah kerangka kerja 4 tahap dalam menyelesaikan masalah desain sistem yang ambigu. Menganalisis arsitektur sistem nyata dari dasar: kalkulasi kapasitas komputasi dan bandwidth, strategi partisi basis data (sharding), konsistensi cache Redis, penyeimbang beban global (Anycast DNS & CDN), serta mitigasi single-point-of-failure pada klaster multi-region.',
  NULL, 'system_design_interview.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  204, 30,
  '[E-Book] Full-Stack Modern dengan Go & Next.js: Dari Nol Hingga Deployment VPS Produksi',
  'Eko Kurniawan Khannedy, Sandhika Galih ; penyelia, Tim Galura Software House',
  'Cet. 1 Edisi Digital',
  '978-623-01-3892-9', 203, '2024',
  '1 file PDF (xx, 412 hlm. : ilus. ; 25 cm)',
  'Seri Pengembang Web Indonesia Modern; Jilid 1',
  'EB 005.133 KHA f', 'id', 'pembelian', 204, '005.133',
  'Kombinasi antara efisiensi kompilasi native bahasa Go dan kekayaan interaksi antarmuka Next.js telah menjadi standar emas baru dalam rekayasa aplikasi web modern yang menuntut performa puncak dan SEO optimal. Membahas pembuatan backend API Go dengan framework Fiber, manajemen koneksi database PostgreSQL via ORM GORM, otentikasi JWT aman berbasis HTTP-Only Cookie, manajemen state TanStack Query pada Next.js Server Components, hingga otomatisasi deployment menggunakan Docker dan Nginx Reverse Proxy.',
  NULL, 'fullstack_go_nextjs.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  205, 30,
  '[E-Book] Clean Architecture & Pola Desain Perangkat Lunak Berkelanjutan',
  'Robert C. Martin (Uncle Bob) ; alih bahasa teknis, Dr. Ir. Rian Pratama, M.Sc.',
  'Edisi Digital Masterclass',
  '978-0-13-449416-6', 202, '2023',
  '1 file PDF (xxiv, 432 hlm. : ilus. ; 25 cm)',
  'Seri Praktik Rekayasa Perangkat Lunak Profesional; Jilid 3',
  'EB 005.1 MAR c', 'id', 'pembelian', 205, '005.1',
  'Karya legendaris Uncle Bob yang menjabarkan aturan universal struktur perangkat lunak yang tahan terhadap perubahan zaman. Memaparkan bagaimana memisahkan logika bisnis murni dari kerangka kerja (framework), basis data, antarmuka pengguna, dan pustaka eksternal lainnya. Menganalisis prinsip SOLID secara mendalam, Dependency Inversion Principle, Boundary Objects, Entity Boundaries, serta strategi penulisan tes unit cepat yang berjalan murni dalam memori tanpa memerlukan koneksi ke database atau layanan eksternal.',
  NULL, 'clean_architecture.pdf', 0, 0, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  206, 30,
  '[E-Book] Cybersecurity Essentials: Analisis Serangan Siber, Penetration Testing & Server Hardening',
  'Dr. Ir. Rian Pratama, M.Sc., Kevin Mitnick ; editor, Tim Galura CERT',
  'Cet. 2 Edisi Digital',
  '978-623-01-3893-6', 205, '2024',
  '1 file PDF (xxii, 388 hlm. : ilus. ; 25 cm)',
  'Seri Pertahanan Siber Nasional; Jilid 1',
  'EB 005.8 PRA c', 'id', 'pembelian', 203, '005.8',
  'Di era digital yang serba terhubung, keamanan informasi bukan lagi opsi tambahan melainkan fondasi kelangsungan bisnis. Buku ini mengupas metodologi serangan siber modern dan langkah preventif berstandar industri perbankan dan militer. Menyajikan panduan praktis hardening server Linux Ubuntu, mitigasi serangan DDoS lapis 4 dan 7, konfigurasi firewall UFW dan deteksi intrusi Fail2ban, analisis log forensik auditd/ELK, pencegahan SQL Injection, XSS, SSRF, serta penerapan prinsip Zero Trust Network Access.',
  NULL, 'cybersecurity_essentials.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  207, 30,
  '[E-Book] DevOps & GitOps Mastery: Otomasi CI/CD dengan GitHub Actions, Ansible & Kubernetes',
  'Brendan Burns, Kelsey Hightower ; alih bahasa, Tim SRE Galura Cloud',
  'Edisi Digital 2024',
  '978-1-492-05647-8', 203, '2024',
  '1 file PDF (xxvi, 420 hlm. : ilus. ; 25 cm)',
  'Seri Otomasi Infrastruktur Awan; Jilid 2',
  'EB 005.12 BUR d', 'id', 'pembelian', 202, '005.12',
  'DevOps dan GitOps telah mengubah total cara tim perekayasa perangkat lunak mengalirkan inovasi dari repositori kode menuju lingkungan produksi secara instan, konsisten, dan aman tanpa intervensi manual yang rentan kesalahan manusia. Buku ini memandu pembaca membangun pipeline CI/CD tangguh menggunakan GitHub Actions, melakukan provisioning server otomatis dengan Ansible Playbook idempotent, mengelola konfigurasi deklaratif GitOps via ArgoCD, serta merancang strategi rilis Blue-Green dan Canary Deployment pada Kubernetes.',
  NULL, 'devops_gitops_mastery.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  208, 30,
  '[E-Book] Data Science & Machine Learning Praktis dengan Python, Pandas dan Scikit-Learn',
  'Andrew Ng, Ph.D., Aurélien Géron ; editor, Dr. Ir. Rian Pratama, M.Sc.',
  'Cet. 1 Edisi Digital',
  '978-1-492-03264-9', 201, '2024',
  '1 file PDF (xxviii, 464 hlm. : ilus. ; 25 cm)',
  'Seri Sains Data & Kecerdasan Mesin; Jilid 1',
  'EB 006.3 NG d', 'id', 'pembelian', 201, '006.3',
  'Sains data telah menjadi motor penggerak utama dalam pengambilan keputusan bisnis modern. Buku ini menyajikan panduan praktis dan matematis yang seimbang dalam menerapkan algoritma machine learning menggunakan ekosistem bahasa Python. Menjelaskan eksplorasi data komprehensif menggunakan Pandas dan NumPy, visualisasi interaktif Seaborn, prapemrosesan data kotor, rekayasa fitur (feature engineering), model regresi, pohon keputusan (Random Forest & XGBoost), clustering, hingga deployment model melalui API FastAPI.',
  NULL, 'data_science_python.pdf', 0, 0, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  209, 30,
  '[E-Book] Desain UI/UX & Design Systems Modern: Menyelaraskan Estetika Visual dengan Kebutuhan Pengguna',
  'Dr. Ayu Lestari, M.T.I., Don Norman ; editor, Tim Desain Produk Galura',
  'Edisi Digital 2024',
  '978-623-01-3894-3', 203, '2024',
  '1 file PDF (xviii, 348 hlm. : ilus. ; 25 cm)',
  'Seri Desain Antarmuka Produk Digital; Jilid 1',
  'EB 741.6 LES d', 'id', 'pembelian', 204, '741.6',
  'Desain antarmuka bukan sekadar mempercantik tampilan visual, melainkan menciptakan jembatan kognitif yang intuitif antara kebutuhan pengguna dan kapabilitas fungsional teknologi. Buku ini memandu desainer dan developer menciptakan pengalaman digital yang inklusif dan memikat. Menguraikan tahapan riset pengguna kualitatif dan kuantitatif, usability testing, penyusunan arsitektur informasi, prinsip Atomic Design di Figma, pembuatan tokens desain CSS lintas platform, serta pemenuhan kepatuhan aksesibilitas web internasional WCAG 2.1 Level AA.',
  NULL, 'ui_ux_design_systems.pdf', 0, 0, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  210, 30,
  '[E-Book] Strategi Skalabilitas Bisnis Startup Teknologi: Dari Validasi Pasar Hingga Pendanaan Seri A',
  'Gita Wirjawan, Eric Ries ; penyunting, Tim Modal Ventura Galura',
  'Cet. 2 Edisi Digital',
  '978-623-01-3895-0', 206, '2024',
  '1 file PDF (xxii, 360 hlm. : ilus. ; 25 cm)',
  'Seri Manajemen Eksekutif & Kewirausahaan Digital; Jilid 2',
  'EB 658.4 WIR s', 'id', 'pembelian', 203, '658.4',
  'Membangun startup teknologi bukan hanya tentang memiliki ide cemerlang, melainkan tentang eksekusi disiplin dalam memvalidasi hipotesis pasar dan membangun mesin pertumbuhan bisnis yang berkelanjutan. Buku ini mengulas strategi navigating lembah kematian (valley of death) startup. Menjabarkan metodologi Lean Startup, perhitungan unit economics presisi (Customer Acquisition Cost, Lifetime Value, Payback Period), analisis retensi berbasis kurva kohor, strategi penetapan harga B2B/B2C, serta tips negosiasi Term Sheet pada putaran pendanaan Seed hingga Seri A.',
  NULL, 'tech_startup_scale.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  211, 30,
  '[E-Book] Pengembangan Aplikasi Mobile Lintas Platform dengan Flutter & Dart: Arsitektur BLoC & Offline-First',
  'Donny Prakoso, Angela Yu ; editor, Tim Mobile Galura',
  'Edisi Digital 2024',
  '978-623-01-3896-7', 203, '2024',
  '1 file PDF (xxiv, 416 hlm. : ilus. ; 25 cm)',
  'Seri Pemrograman Mobile Terapan; Jilid 1',
  'EB 005.26 PRA p', 'id', 'pembelian', 204, '005.26',
  'Ekosistem Flutter telah merevolusi kecepatan pengembangan aplikasi mobile dengan menghasilkan kode terkompilasi native ke iOS dan Android dari satu basis kode Dart tunggal. Buku ini menjadi pedoman lengkap bagi pengembang yang ingin melangkah dari aplikasi sederhana ke kelas enterprise. Menitikberatkan pada pola arsitektur BLoC (Business Logic Component), manajemen state deterministik, strategi penyimpanan lokal offline-first menggunakan SQLite/Isar, sinkronisasi latar belakang dengan WorkManager, serta integrasi pustaka animasi interaktif dan CI/CD rilis otomatis ke Play Store dan App Store.',
  NULL, 'mobile_app_flutter.pdf', 0, 0, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  212, 30,
  '[E-Book] Database Deep Dive: Optimasi Query SQL, Desain Indeks B-Tree & Arsitektur Sharding',
  'Alex Xu, Baron Schwartz ; alih bahasa, Tim DBA Galura Core',
  'Cet. 1 Edisi Digital',
  '978-1-492-08051-0', 201, '2023',
  '1 file PDF (xxviii, 490 hlm. : ilus. ; 25 cm)',
  'Seri Teknologi Database Skala Besar; Jilid 2',
  'EB 005.74 XU d', 'id', 'pembelian', 202, '005.74',
  'Di balik setiap aplikasi berskala masif, terdapat basis data relasional yang harus mampu melayani puluhan ribu transaksi konkuren tanpa degradasi performa atau korupsi data. Buku ini membongkar rahasia internal mesin database relasional (khususnya MySQL dan MariaDB). Menjelaskan cara kerja engine InnoDB, struktur halaman indeks B+ Tree dan Clustered Index, optimasi query lambat menggunakan EXPLAIN ANALYZE, isolasi transaksi ACID, strategi penanganan deadlock dan lock escalation, serta teknik partisi horizontal (sharding) dan replikasi data multi-region.',
  NULL, 'database_deep_dive.pdf', 0, 0, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  213, 30,
  '[E-Book] Kepemimpinan Digital & Transformasi Budaya: Membangun Tim Kolaboratif Era AI',
  'Satya Nadella, Amy Edmondson ; editor, Tim Pengembangan SDM Galura',
  'Cet. 1 Edisi Digital',
  '978-0-06-265885-2', 207, '2024',
  '1 file PDF (xx, 310 hlm. : ilus. ; 25 cm)',
  'Seri Transformasi Manajemen Korporasi; Jilid 1',
  'EB 658.409 NAD k', 'id', 'pembelian', 206, '658.409',
  'Transformasi digital bukan tentang pembelian perangkat lunak baru atau langganan cloud termutakhir, melainkan tentang transformasi cara berpikir manusia dan keberanian kepemimpinan dalam merestrukturisasi budaya kerja organisasi agar adaptif terhadap disrupsi AI. Mengulas pengalaman kepemimpinan mentransformasikan raksasa teknologi menuju budaya Learn-it-all daripada Know-it-all, menciptakan keamanan psikologis (psychological safety) di mana kegagalan eksperimen dipelajari bukan dihukum, serta mengelola kerja kolaboratif asinkron melintasi zona waktu.',
  NULL, 'digital_leadership.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  214, 30,
  '[E-Book] Internet of Things (IoT) Industri 4.0: Sensor Cerdas, Protokol MQTT & Edge Computing',
  'Dr. Ir. Rian Pratama, M.Sc., Dirk Slama ; penyunting, Lab IoT & Mekatronika Galura',
  'Edisi Digital 2024',
  '978-623-01-3897-4', 208, '2024',
  '1 file PDF (xxiv, 372 hlm. : ilus. ; 25 cm)',
  'Seri Otomasi Industri & Sistem Tertanam; Jilid 1',
  'EB 004.678 PRA i', 'id', 'pembelian', 207, '004.678',
  'Revolusi Industri 4.0 bertumpu pada interkoneksi cerdas antara mesin-mesin fisik di lantai pabrik dengan platform analitik awan. Buku ini menyajikan arsitektur telemetri industri komprehensif yang dirancang untuk keandalan tinggi dan latensi rendah. Menjelaskan pemilihan mikrokontroler industri (ESP32, STM32, Raspberry Pi Compute Module), komunikasi data sensor via protokol MQTT/CoAP dengan broker Mosquitto, penyimpanan telemetri pada time-series database InfluxDB/TimescaleDB, komputasi tepi (edge computing), dan enkripsi perangkat keras TPM/Axiom.',
  NULL, 'iot_industry_40.pdf', 0, 0, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
),
(
  215, 30,
  '[E-Book] Metodologi Riset Komputasi & Panduan Publikasi Ilmiah Jurnal Terindeks Scopus/WoS',
  'Dr. Ir. Rian Pratama, M.Sc., Prof. Dr. Ir. Suhono H. Supangkat',
  'Cet. 2 Edisi Digital',
  '978-623-01-3898-1', 210, '2024',
  '1 file PDF (xx, 330 hlm. : ilus. ; 25 cm)',
  'Seri Publikasi Ilmiah & Akademik Pascasarjana; Jilid 1',
  'EB 001.42 PRA m', 'id', 'pembelian', 203, '001.42',
  'Publikasi pada jurnal bereputasi tinggi terindeks Scopus kuartil atas (Q1/Q2) dan Web of Science menuntut metodologi riset yang ketat, orisinalitas kontribusi ilmiah yang terukur, serta penyajian naskah artikel yang memenuhi standar akademis internasional. Buku ini membimbing akademisi, peneliti, dan mahasiswa pascasarjana merumuskan kontribusi penelitian (novelty), melaksanakan Systematic Literature Review berpedoman protokol PRISMA, merancang uji coba eksperimen komparatif berbasis benchmark standar, serta menanggapi komentar reviewer secara elegan dan profesional.',
  NULL, 'metodologi_riset_scopus.pdf', 0, 1, NULL, 0,
  'Format: PDF Vektor Digital (Searchable Text, High-DPI Diagram) | Proteksi: Read-Only Watermarked | Resolusi: 300 DPI | Lisensi: Akses Terbuka Perpustakaan Galura',
  20, 2, 16, NOW(), NOW(), 1
)
ON DUPLICATE KEY UPDATE
  `title`=VALUES(`title`),
  `sor`=VALUES(`sor`),
  `edition`=VALUES(`edition`),
  `isbn_issn`=VALUES(`isbn_issn`),
  `publisher_id`=VALUES(`publisher_id`),
  `publish_year`=VALUES(`publish_year`),
  `collation`=VALUES(`collation`),
  `series_title`=VALUES(`series_title`),
  `call_number`=VALUES(`call_number`),
  `language_id`=VALUES(`language_id`),
  `source`=VALUES(`source`),
  `publish_place_id`=VALUES(`publish_place_id`),
  `classification`=VALUES(`classification`),
  `notes`=VALUES(`notes`),
  `file_att`=VALUES(`file_att`),
  `opac_hide`=VALUES(`opac_hide`),
  `promoted`=VALUES(`promoted`),
  `labels`=VALUES(`labels`),
  `spec_detail_info`=VALUES(`spec_detail_info`),
  `content_type_id`=VALUES(`content_type_id`),
  `media_type_id`=VALUES(`media_type_id`),
  `carrier_type_id`=VALUES(`carrier_type_id`),
  `last_update`=NOW();

-- 6. Relasi Penulis Bibliografi (biblio_author)
DELETE FROM `biblio_author` WHERE `biblio_id` BETWEEN 201 AND 215;
INSERT INTO `biblio_author` (`biblio_id`, `author_id`, `level`) VALUES
(201, 201, 1),
(201, 202, 2),
(202, 203, 1),
(202, 204, 2),
(203, 205, 1),
(203, 206, 2),
(204, 207, 1),
(204, 208, 2),
(205, 209, 1),
(206, 203, 1),
(206, 210, 2),
(207, 211, 1),
(207, 212, 2),
(208, 204, 1),
(208, 213, 2),
(209, 214, 1),
(209, 215, 2),
(210, 216, 1),
(210, 217, 2),
(211, 218, 1),
(211, 219, 2),
(212, 205, 1),
(212, 220, 2),
(213, 221, 1),
(213, 222, 2),
(214, 203, 1),
(214, 223, 2),
(215, 203, 1),
(215, 224, 2);

-- 7. Relasi Topik Bibliografi (biblio_topic)
DELETE FROM `biblio_topic` WHERE `biblio_id` BETWEEN 201 AND 215;
INSERT INTO `biblio_topic` (`biblio_id`, `topic_id`, `level`) VALUES
(201, 201, 1),
(201, 207, 2),
(202, 202, 1),
(202, 208, 2),
(203, 203, 1),
(203, 212, 2),
(204, 204, 1),
(204, 201, 2),
(205, 205, 1),
(205, 204, 2),
(206, 206, 1),
(206, 207, 2),
(207, 207, 1),
(207, 201, 2),
(208, 208, 1),
(208, 202, 2),
(209, 209, 1),
(209, 204, 2),
(210, 210, 1),
(210, 213, 2),
(211, 211, 1),
(211, 204, 2),
(212, 212, 1),
(212, 203, 2),
(213, 213, 1),
(213, 210, 2),
(214, 214, 1),
(214, 201, 2),
(215, 215, 1),
(215, 208, 2);

-- 8. Berkas E-Book Digital (files)
INSERT INTO `files` (
  `file_id`, `file_title`, `file_name`, `file_url`, `file_dir`, `mime_type`, `file_desc`, `file_key`, `uploader_id`, `input_date`, `last_update`
) VALUES
(201, 'E-Book PDF: Arsitektur Microservices & Cloud-Native (Edisi Lengkap)', 'microservices_cloud_native.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(202, 'E-Book PDF: Rekayasa Prompt & Implementasi LLM Modern (Edisi Lengkap)', 'prompt_engineering_llm.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(203, 'E-Book PDF: System Design Interview Scale Handbook (Edisi Lengkap)', 'system_design_interview.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(204, 'E-Book PDF: Full-Stack Modern dengan Go & Next.js (Edisi Lengkap)', 'fullstack_go_nextjs.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(205, 'E-Book PDF: Clean Architecture & Software Design Patterns (Edisi Lengkap)', 'clean_architecture.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(206, 'E-Book PDF: Cybersecurity Essentials Handbook (Edisi Lengkap)', 'cybersecurity_essentials.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(207, 'E-Book PDF: DevOps & GitOps Automation Mastery (Edisi Lengkap)', 'devops_gitops_mastery.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(208, 'E-Book PDF: Data Science & Machine Learning Python (Edisi Lengkap)', 'data_science_python.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(209, 'E-Book PDF: UI/UX Design Systems & User Research (Edisi Lengkap)', 'ui_ux_design_systems.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(210, 'E-Book PDF: Strategi Skalabilitas Bisnis Startup Teknologi (Edisi Lengkap)', 'tech_startup_scale.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(211, 'E-Book PDF: Pengembangan Aplikasi Mobile Flutter & Dart (Edisi Lengkap)', 'mobile_app_flutter.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(212, 'E-Book PDF: Database Deep Dive & Query Optimization (Edisi Lengkap)', 'database_deep_dive.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(213, 'E-Book PDF: Kepemimpinan Digital & Inovasi Kolaboratif (Edisi Lengkap)', 'digital_leadership.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(214, 'E-Book PDF: Internet of Things (IoT) Industri 4.0 (Edisi Lengkap)', 'iot_industry_40.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW()),
(215, 'E-Book PDF: Metodologi Riset Komputasi Scopus (Edisi Lengkap)', 'metodologi_riset_scopus.pdf', NULL, '', 'application/pdf', 'Dokumen e-book digital resmi format PDF. Dilengkapi cover, metadata bibliografi KDT, daftar isi lengkap, dan cuplikan Bab 1.', '', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `file_title`=VALUES(`file_title`),
  `file_name`=VALUES(`file_name`),
  `file_dir`=VALUES(`file_dir`),
  `mime_type`=VALUES(`mime_type`),
  `file_desc`=VALUES(`file_desc`),
  `last_update`=NOW();

-- 9. Lampiran Attachment Bibliografi E-Book (biblio_attachment)
DELETE FROM `biblio_attachment` WHERE `biblio_id` BETWEEN 201 AND 215;
INSERT INTO `biblio_attachment` (`biblio_id`, `file_id`, `placement`, `access_type`, `access_limit`) VALUES
(201, 201, 'embed', 'public', NULL),
(202, 202, 'embed', 'public', NULL),
(203, 203, 'embed', 'public', NULL),
(204, 204, 'embed', 'public', NULL),
(205, 205, 'embed', 'public', NULL),
(206, 206, 'embed', 'public', NULL),
(207, 207, 'embed', 'public', NULL),
(208, 208, 'embed', 'public', NULL),
(209, 209, 'embed', 'public', NULL),
(210, 210, 'embed', 'public', NULL),
(211, 211, 'embed', 'public', NULL),
(212, 212, 'embed', 'public', NULL),
(213, 213, 'embed', 'public', NULL),
(214, 214, 'embed', 'public', NULL),
(215, 215, 'embed', 'public', NULL);

-- 10. Eksemplar Item Digital E-Book (item)
DELETE FROM `item` WHERE `biblio_id` BETWEEN 201 AND 215;
INSERT INTO `item` (`item_id`, `biblio_id`, `coll_type_id`, `item_code`, `inventory_code`, `received_date`, `supplier_id`, `order_no`, `location_id`, `item_status_id`, `site`, `source`, `price`, `price_currency`, `input_date`, `last_update`) VALUES
(201, 201, 1, 'EB-001', 'INV/EB/2024/001', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(202, 202, 1, 'EB-002', 'INV/EB/2024/002', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(203, 203, 1, 'EB-003', 'INV/EB/2024/003', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(204, 204, 1, 'EB-004', 'INV/EB/2024/004', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(205, 205, 1, 'EB-005', 'INV/EB/2024/005', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(206, 206, 1, 'EB-006', 'INV/EB/2024/006', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(207, 207, 1, 'EB-007', 'INV/EB/2024/007', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(208, 208, 1, 'EB-008', 'INV/EB/2024/008', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(209, 209, 1, 'EB-009', 'INV/EB/2024/009', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(210, 210, 1, 'EB-010', 'INV/EB/2024/010', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(211, 211, 1, 'EB-011', 'INV/EB/2024/011', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(212, 212, 1, 'EB-012', 'INV/EB/2024/012', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(213, 213, 1, 'EB-013', 'INV/EB/2024/013', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(214, 214, 1, 'EB-014', 'INV/EB/2024/014', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW()),
(215, 215, 1, 'EB-015', 'INV/EB/2024/015', CURDATE(), '0', 'PO-EB-2024-01', 'SL', '0', 'Server Digital Galura', 1, 0, 'Rupiah', NOW(), NOW())
ON DUPLICATE KEY UPDATE `last_update`=NOW();
